"""
Bursary-Bridge SRS content.

Single source of truth. Section 2.2 (informal use cases), Section 3.2 (formal
requirement tables) and every use case diagram are all generated from
USE_CASES below, so the three views can never drift apart.
"""

PROJECT = "Bursary-Bridge"
SUBTITLE = "A Bursary and Scholarship Matching Platform"

# ---------------------------------------------------------------------------
# 1.3 Glossary
# ---------------------------------------------------------------------------
GLOSSARY = [
    ("Applicant", "A Student who has submitted an application to a Funding Programme."),
    ("Application", "A Student's formal request for funding under a specific Funding Programme. An application carries a status, the profile the Student applied with, answers to programme questions and any attached documents."),
    ("Beneficiary", "An Applicant who has been selected to receive funding under a Funding Programme."),
    ("Corporate User", "A representative of an Organisation who administers that Organisation's Funding Programmes on the system. Also referred to as the Funder."),
    ("Database", "The collection of all information monitored by this system."),
    ("Eligibility Rule", "The machine-readable set of conditions attached to a Funding Programme, covering supported institutions and courses, qualification level, minimum academic average, year of study, citizenship, household income and province."),
    ("Eligibility Outcome", "The verdict returned when an Applicant is evaluated against a programme's Eligibility Rule: Eligible, Not Eligible, or Pending Verification."),
    ("Funding Programme", "A bursary, scholarship or grant published by an Organisation, to which Students may apply."),
    ("Institution", "A recognised South African university, university of technology or TVET college held in the standardised catalogue."),
    ("Match Score", "A percentage from 0 to 100 expressing how closely a Student's profile fits a Funding Programme, produced by the Matching Engine."),
    ("Matching Engine", "The component that scores a Student profile against a Funding Programme across six weighted criteria and returns both the score and the reasons behind it."),
    ("Organisation", "A corporation, foundation, NGO or other body that funds education through the system."),
    ("Programme", "A standardised course of study, such as Computer Science, held in the catalogue. Distinct from a Funding Programme."),
    ("Profile Strength", "A percentage indicating how complete a Student's profile is, used to prompt the Student to supply information that would improve their matches."),
    ("Shortlist", "The set of Applicants an Organisation is actively considering for a Funding Programme."),
    ("Software Requirements Specification", "A document that completely describes all of the functions of a proposed system and the constraints under which it must operate."),
    ("Stakeholder", "Any person with an interest in the project who is not a developer."),
    ("Student", "A learner seeking funding for tertiary study, who holds a profile on the system."),
    ("Study Preference", "A course paired with the institution at which the Student intends to study it. A Student may hold a maximum of six."),
    ("User", "A Student or a Corporate User."),
]

# ---------------------------------------------------------------------------
# 2.2 / 3.2  Use cases
#
# group:  common | student | corporate
# actor:  the label drawn on the use case diagram
# ---------------------------------------------------------------------------
USE_CASES = [
    # ---------------------------------------------------------------- common
    dict(
        id="UC-01", name="Log In", group="common", actor="User",
        brief="A registered User authenticates and is taken to the part of the system that matches their role.",
        pre="Before this use case can be initiated, the User has already registered an account and has accessed the Bursary-Bridge login page.",
        steps=[
            "The User enters their email address and password.",
            "The System verifies the credentials against the stored password hash.",
            "The System creates a session and issues a session cookie.",
            "The System directs a Student to the Student Dashboard and a Corporate User to the Corporate Dashboard.",
            "If the User has not finished their profile, the System returns them to the step at which they stopped.",
        ],
        trigger="The User submits the login form.",
        precondition="The User has a registered account and is not currently signed in.",
        basic_path=[
            "The User enters an email address and password.",
            "The System looks up the account by email address.",
            "The System compares the supplied password against the stored bcrypt hash.",
            "The System creates a session record and returns a signed, HTTP-only session cookie.",
            "The System redirects the User according to their role and onboarding state.",
        ],
        alternative_paths="In step 5, if the User has not completed onboarding, the System redirects to the outstanding step rather than the dashboard.",
        postcondition="The User is authenticated and holds a valid session.",
        exception_paths="If the email address is not registered, or the password does not match, the System returns the same message in both cases so that the endpoint cannot be used to discover which email addresses hold accounts. After ten failed attempts from one address, or six against one account, further attempts are refused for five minutes.",
        other="Sessions expire after fourteen days. Only a hash of the session token is stored, so a copy of the database cannot be replayed as a login.",
    ),
    dict(
        id="UC-02", name="Log Out", group="common", actor="User",
        brief="A User ends their session.",
        pre="Before this use case can be initiated, the User is signed in.",
        steps=[
            "The User selects Log out from the navigation sidebar.",
            "The System deletes the session record.",
            "The System clears the session cookie and returns the User to the login page.",
        ],
        trigger="The User selects Log out.",
        precondition="The User holds a valid session.",
        basic_path=[
            "The System deletes the session record from the database.",
            "The System clears the session cookie in the browser.",
            "The System returns the User to the login page.",
        ],
        alternative_paths="None.",
        postcondition="The session no longer exists and the cookie cannot be reused.",
        exception_paths="If the session has already expired, the System still clears the cookie and returns the User to the login page.",
        other="Because the session is deleted on the server, logging out invalidates the cookie immediately rather than relying on its expiry.",
    ),
    dict(
        id="UC-03", name="Manage Account Settings", group="common", actor="User",
        brief="A User updates their contact details, notification preference or password.",
        pre="Before this use case can be initiated, the User has signed in and accessed the Settings page.",
        steps=[
            "The User edits their first name, last name, email address, mobile number or email notification preference.",
            "The System validates the submitted values and saves them.",
            "If the email address changed, the System marks the address unverified and sends a new verification email.",
            "The User may instead choose to change their password by supplying the current password and a new one twice.",
            "The System verifies the current password, stores the new hash and ends every other session.",
        ],
        trigger="The User submits the account details form or the change password form.",
        precondition="The User holds a valid session.",
        basic_path=[
            "The System validates the submitted values on the server.",
            "For a details change, the System writes the new values to the User record.",
            "For a password change, the System verifies the current password, hashes the new password and stores it.",
            "The System confirms the change to the User.",
        ],
        alternative_paths="In step 2, if the email address has changed, the verified flag is cleared and a fresh verification email is sent.",
        postcondition="The account record reflects the change. After a password change every other session has been invalidated.",
        exception_paths="If the new email address already belongs to another account, the change is refused. If the current password is incorrect, the password change is refused.",
        other="Changing a password deliberately signs the User out of every device, so that a stolen session cannot survive the change.",
    ),
    dict(
        id="UC-04", name="View Notifications", group="common", actor="User",
        brief="A User reads the notifications the System has raised for them and marks them as read.",
        pre="Before this use case can be initiated, the User has signed in.",
        steps=[
            "The User selects Notifications from the sidebar.",
            "The System presents the User's notifications, newest first, with unread items highlighted.",
            "The User selects a notification.",
            "The System marks that notification read and follows its link.",
            "The User may instead choose to mark every notification as read.",
        ],
        trigger="The User opens the Notifications page.",
        precondition="The User holds a valid session.",
        basic_path=[
            "The System retrieves the fifty most recent notifications belonging to this User.",
            "The System presents them newest first, showing the unread count.",
            "The User selects a notification, or selects to mark all as read.",
            "The System records the read timestamp and, where the notification carries a link, navigates to it.",
        ],
        alternative_paths="The User may mark every unread notification as read in a single action.",
        postcondition="The selected notifications are marked read and the unread badge is updated.",
        exception_paths="A User can only ever read notifications addressed to their own account; a request for another User's notification affects nothing.",
        other="Notifications are also mirrored to email when the User has left email notifications enabled.",
    ),

    # --------------------------------------------------------------- student
    dict(
        id="UC-05", name="Register Student Account", group="student", actor="Student",
        brief="A prospective Student creates an account so that they can build a funding profile.",
        pre="Before this use case can be initiated, the visitor has accessed the Bursary-Bridge website and chosen to sign up as a Student.",
        steps=[
            "The Student supplies a first name, last name, email address, mobile number and password, and confirms the password.",
            "The Student indicates whether to receive funding opportunity notifications by email.",
            "The Student accepts the Terms of Service and Privacy Notice.",
            "The System validates every field and confirms that the email address is not already registered.",
            "The System creates the account, an empty Student profile and a session, and sends a verification email.",
            "The System presents the Check your email screen.",
        ],
        trigger="The Student submits the student registration form.",
        precondition="The visitor is not signed in and does not hold an account under the supplied email address.",
        basic_path=[
            "The System validates the name fields, the email address, the South African mobile number and the password.",
            "The System confirms that the two password entries match and that the terms have been accepted.",
            "The System confirms that no account already exists for the email address.",
            "The System hashes the password using bcrypt and creates the User record with the role Student.",
            "The System creates an empty Student profile positioned at the first onboarding step.",
            "The System creates a session, sends a verification email and presents the verification screen.",
        ],
        alternative_paths="None.",
        postcondition="A Student account and an empty profile exist, the Student is signed in, and a verification email has been sent.",
        exception_paths="If the email address is already registered the System refuses the registration and invites the visitor to sign in instead. If any field fails validation the System returns the specific field errors and creates nothing. More than five registration attempts from one address within ten minutes are refused.",
        other="The password must be at least eight characters and contain an upper case letter, a lower case letter and a digit. The same rules are enforced on the server and shown as a live checklist beneath the field.",
    ),
    dict(
        id="UC-06", name="Verify Email Address", group="student", actor="Student",
        brief="The Student confirms ownership of the email address supplied at registration.",
        pre="Before this use case can be initiated, the Student has registered and the System has sent a verification email.",
        steps=[
            "The Student opens the verification email and follows the link.",
            "The System reads the token from the link and compares its hash against the stored token.",
            "The System confirms that the token has not expired.",
            "The System marks the email address verified and deletes the token.",
            "The System takes the Student to the first step of the profile.",
        ],
        trigger="The Student follows the verification link, or requests that the email be sent again.",
        precondition="A verification token exists for the account and has not yet been used.",
        basic_path=[
            "The System hashes the token from the link and looks up the matching record.",
            "The System confirms the token has not expired.",
            "The System sets the verified timestamp on the User record.",
            "The System deletes the token so that the link cannot be used twice.",
            "The System redirects the Student to the first profile step.",
        ],
        alternative_paths="The Student may request a fresh verification email, which replaces any existing token. No more than three such requests are accepted in five minutes.",
        postcondition="The email address is recorded as verified and the token has been consumed.",
        exception_paths="An unrecognised token is rejected. A token older than twenty-four hours is rejected and deleted, and the Student is invited to request a new one.",
        other="Verification is not enforced before the Student may continue, so an email delivery problem never blocks the journey. Only the hash of the token is stored.",
    ),
    dict(
        id="UC-07", name="Complete Student Profile", group="student", actor="Student",
        brief="The Student supplies the information the Matching Engine needs, one step at a time.",
        pre="Before this use case can be initiated, the Student has registered and is signed in.",
        steps=[
            "The Student states their education stage, the qualification level they intend to study and their study status. If they are already enrolled, the System also asks for their current institution, current programme and year of study.",
            "The Student records their study preferences, as described in Section 2.2.2, Manage Study Preferences.",
            "The Student gives their latest academic average, or indicates that they do not know it, and selects the results and achievements they hold.",
            "The Student selects what they need funding for and describes their current funding situation.",
            "The Student selects a household income band and, optionally, date of birth, citizenship and further eligibility information.",
            "The Student selects their province, city or town, expected study location and up to five career interests.",
            "The System presents the whole profile for review, with a link to edit any section.",
            "The Student confirms, and the System opens the Student Dashboard.",
        ],
        trigger="The Student submits any step of the profile.",
        precondition="The Student holds a valid session and a Student profile record exists.",
        basic_path=[
            "The System presents the current step with any previously saved values filled in.",
            "The Student completes the step and submits it.",
            "The System validates the step against the schema that governs that step alone.",
            "The System saves the values, recalculates profile strength and advances the stored position.",
            "The System presents the next step, and after the last step presents the review screen.",
            "On confirmation the System marks the profile complete and opens the Dashboard.",
        ],
        alternative_paths="A learner in Grade 10 or Grade 11 is not asked for a tertiary qualification level. A Student who is not currently enrolled is not asked for a current institution, programme or year of study. The Student may leave at any point using Save and Exit and resume later at the same step.",
        postcondition="The profile holds the supplied information, profile strength has been recalculated, and once the review step is confirmed the Student may see matched opportunities.",
        exception_paths="A step that fails validation is redisplayed with the specific field errors and nothing is saved. The review step is refused if no education stage has been recorded or no study preference exists.",
        other="Each step is validated on the server against its own schema, so a request cannot write a field belonging to a different step. Registration deliberately does not ask for a residential address, identity number, banking details or financial records; such information is requested only when a specific application needs it.",
    ),
    dict(
        id="UC-08", name="Manage Study Preferences", group="student", actor="Student",
        brief="The Student records up to six courses, each paired with the institution at which they intend to study it.",
        pre="Before this use case can be initiated, the Student has signed in and reached the Study Preferences step or opened it from their profile.",
        steps=[
            "The System presents the Student's existing preferences, numbered in order.",
            "The Student selects a course from the standardised catalogue.",
            "The Student selects the institution at which they intend to study that course.",
            "The Student repeats steps 2 and 3 for each combination they are considering, up to six.",
            "The Student may remove a preference or change either half of a pair.",
            "The System saves the list, renumbering the preferences so that they remain in order.",
        ],
        trigger="The Student submits the study preferences form.",
        precondition="The Student holds a valid session and a Student profile exists.",
        basic_path=[
            "The System presents the current preferences and the catalogue of courses and institutions.",
            "The Student adds, edits, removes or reorders preferences.",
            "The System confirms that every course and institution exists in the catalogue.",
            "The System confirms that no two preferences name the same course and institution pair.",
            "The System replaces the stored list in a single transaction and renumbers it from one.",
            "The System recalculates profile strength.",
        ],
        alternative_paths="A preference that is missing either its course or its institution is not saved; the System tells the Student that the incomplete rows will be discarded.",
        postcondition="The Student holds between one and six numbered study preferences, each a valid course and institution pair.",
        exception_paths="A seventh preference is refused. A duplicate course and institution pair is refused. A course or institution that is not in the catalogue is refused.",
        other="A study preference is stored as a pair, never as two unrelated lists, because a bursary that funds a course at one institution is not necessarily open to the same course elsewhere. The Matching Engine scores both halves of the same pair, so a supported course at an unsupported institution does not count as a full match. The limit of six is enforced on the server.",
    ),
    dict(
        id="UC-09", name="View Matched Opportunities", group="student", actor="Student",
        brief="The Student sees the funding programmes that best fit their profile, ranked, with the reasons behind each score.",
        pre="Before this use case can be initiated, the Student has completed their profile and accessed the Student Dashboard.",
        steps=[
            "The System retrieves every published funding programme that is still open.",
            "The System scores each programme against the Student's profile.",
            "The System presents the number of matches, active applications and approaching deadlines.",
            "The System presents the best matching programmes, each with its match percentage and the criteria that were met.",
            "The System presents profile strength and the sections that would most improve the Student's matches.",
        ],
        trigger="The Student opens the Student Dashboard.",
        precondition="The Student has completed onboarding and holds at least one study preference.",
        basic_path=[
            "The System loads the Student's profile projection.",
            "The System loads every funding programme whose status is published and whose closing date has not passed.",
            "The Matching Engine scores each programme across the six weighted criteria.",
            "The System orders the results by score, highest first.",
            "The System presents the leading matches together with the reasons that produced each score.",
        ],
        alternative_paths="If the Student has already applied to a programme it is marked as applied and excluded from the leading matches.",
        postcondition="The Student has been shown their ranked matches and the reasons behind them.",
        exception_paths="If no programme is currently open, or the profile is too sparse to score, the System explains this and directs the Student to complete the sections that would produce matches.",
        other="A percentage is never presented on its own. Every score is accompanied by the criteria that were met, failed, or could not be evaluated.",
    ),
    dict(
        id="UC-10", name="Search and Filter Opportunities", group="student", actor="Student",
        brief="The Student narrows the list of funding opportunities to those of interest.",
        pre="Before this use case can be initiated, the Student has completed their profile and accessed the Opportunities page.",
        steps=[
            "The System presents every open opportunity, scored and ranked by match.",
            "The Student enters search terms, or selects filters for course, institution, qualification, funding type, what the programme covers, province, minimum match score or closing date.",
            "The Student may choose to hide opportunities already applied for.",
            "The System applies the filters and presents the matching opportunities in pages.",
            "The Student may reorder the results by match, closing date or name.",
        ],
        trigger="The Student enters a search term or changes a filter on the Opportunities page.",
        precondition="The Student has completed onboarding.",
        basic_path=[
            "The System presents the scored opportunities together with the filter controls.",
            "The Student sets one or more filters.",
            "The System applies the filters to the scored set.",
            "The System presents the result count and the first page of results.",
            "The Student pages through the results or changes the ordering.",
        ],
        alternative_paths="The Student may clear all filters and return to the full list at any point.",
        postcondition="The Student is presented with the opportunities that satisfy the chosen filters.",
        exception_paths="If no opportunity satisfies the filters, the System says so and offers to clear them.",
        other="Scoring is performed on the server and results are paged, so the browser never receives the whole catalogue at once.",
    ),
    dict(
        id="UC-11", name="View Opportunity Details", group="student", actor="Student",
        brief="The Student reads the full terms of a funding programme and why they do or do not match it.",
        pre="Before this use case can be initiated, the Student has selected an opportunity from the Dashboard or the Opportunities page.",
        steps=[
            "The System presents the programme name, the funding Organisation, the closing date and what the programme covers.",
            "The System presents the full description, the supported courses and the supported institutions.",
            "The System presents the eligibility requirements, including academic, qualification, year of study, citizenship, financial and geographic conditions.",
            "The System presents the documents the programme requires and how to apply.",
            "The System presents the Student's match score together with every criterion, showing which were met, which were not, and which could not be evaluated.",
        ],
        trigger="The Student selects an opportunity.",
        precondition="The programme is published and the Student has completed onboarding.",
        basic_path=[
            "The System retrieves the programme with its eligibility rule, supported courses and supported institutions.",
            "The Matching Engine scores the Student against that programme.",
            "The System presents the programme detail with the score and the per-criterion explanation.",
            "The System offers to start an application, or shows the existing application if one has been submitted.",
        ],
        alternative_paths="If the Student has already submitted an application, the System offers to view that application instead of starting a new one. If a draft exists, the System offers to continue it.",
        postcondition="The Student understands what the programme funds, who is eligible and how well they match.",
        exception_paths="A programme that is still a draft, or that belongs to no published set, cannot be opened by a Student and returns a not found response.",
        other="The explanation shown to the Student is produced by the same engine that produces the eligibility verdict shown to the funder, so the two can never contradict one another.",
    ),
    dict(
        id="UC-12", name="Apply for Funding", group="student", actor="Student",
        brief="The Student submits an application to a funding programme, reusing the profile they have already built.",
        pre="Before this use case can be initiated, the Student has completed their profile and has opened a published funding programme that is still open.",
        steps=[
            "The System presents the profile that will be sent with the application, for review only, with links to edit any section.",
            "The Student answers any questions specific to this programme.",
            "The Student attaches the documents the programme requires from those already uploaded.",
            "The System presents the application for review, together with the match score.",
            "The Student confirms that the information is accurate and submits.",
            "The System records the application, snapshots the match score and the eligibility verdict, and notifies the Student.",
        ],
        trigger="The Student selects Apply Now on an opportunity.",
        precondition="The programme is published, its closing date has not passed, and the Student has not already submitted an application to it.",
        basic_path=[
            "The System presents the Student's stored profile without asking for it again.",
            "The Student answers the programme's questions and attaches documents.",
            "The Student confirms the declaration and submits.",
            "The System validates the payload, including every required question.",
            "The Matching Engine scores the Student and the Eligibility Service returns a verdict.",
            "The System stores the application with the score, the verdict and the reasons, and sets the status to Submitted.",
            "The System notifies the Student and opens the application tracking page.",
        ],
        alternative_paths="The Student may save a draft at any point and return to it later. A draft may be edited freely until it is submitted.",
        postcondition="An application exists with the status Submitted, carrying the match score and eligibility verdict as they stood at submission.",
        exception_paths="An application to a closed programme is refused. A second application to the same programme is refused. Submission without confirming the declaration, or with a required question unanswered, is refused and the offending fields are named. A document that does not belong to the Student cannot be attached.",
        other="The score is stored at submission so that the funder always sees the match as it stood when the Student applied, even if the Student later edits their profile.",
    ),
    dict(
        id="UC-13", name="Track Application", group="student", actor="Student",
        brief="The Student follows the progress of an application through to a decision.",
        pre="Before this use case can be initiated, the Student has at least one application and has accessed My Applications.",
        steps=[
            "The System presents the Student's applications grouped by status.",
            "The Student selects an application.",
            "The System presents the programme, the funder, the date applied, the closing date and the date of the last change.",
            "The System presents a progress timeline from started through submitted, under review, shortlisted and decided.",
            "The System presents the answers given, the documents attached and the match as it stood at submission.",
        ],
        trigger="The Student opens My Applications or selects an application.",
        precondition="The application belongs to this Student.",
        basic_path=[
            "The System retrieves the applications belonging to this Student.",
            "The System presents them with their statuses and key dates.",
            "The Student selects one.",
            "The System presents the full application, its timeline and the recorded match.",
        ],
        alternative_paths="If the application is still a draft, the System offers to continue it. If the funder has asked for more information, the System presents the request prominently.",
        postcondition="The Student knows the current status of the application and what, if anything, is expected of them.",
        exception_paths="A request for an application that belongs to another Student returns a not found response.",
        other="The statuses are Draft, Submitted, Under Review, Documents Required, Shortlisted, Approved and Unsuccessful.",
    ),
    dict(
        id="UC-14", name="Manage Documents", group="student", actor="Student",
        brief="The Student uploads and maintains the supporting documents funders commonly ask for.",
        pre="Before this use case can be initiated, the Student has signed in and accessed the Documents page.",
        steps=[
            "The System presents the documents the Student has already uploaded.",
            "The Student selects the kind of document and chooses a file.",
            "The System checks the file type and size, stores the file and records it against the Student.",
            "The System recalculates profile strength.",
            "The Student may view or permanently remove any document.",
        ],
        trigger="The Student submits the upload form, or selects to remove a document.",
        precondition="The Student holds a valid session.",
        basic_path=[
            "The Student selects a document type and a file.",
            "The System confirms the file is a PDF or an image and is no larger than five megabytes.",
            "The System writes the file to storage under a key belonging to this Student.",
            "The System records the document and recalculates profile strength.",
        ],
        alternative_paths="The Student may remove a document, which deletes both the record and the stored file. Applications already submitted keep the copy that was attached to them.",
        postcondition="The document is stored against the Student's profile and is available to attach to applications.",
        exception_paths="A file of an unsupported type, an empty file, or a file larger than five megabytes is refused. More than twenty uploads in ten minutes are refused.",
        other="Documents are not required in order to register. They are stored outside the public web root and are released only to the Student who owns them, or to a funder that has received an application the document is attached to.",
    ),

    # ------------------------------------------------------------- corporate
    dict(
        id="UC-15", name="Register Corporate Account", group="corporate", actor="Corporate User",
        brief="A representative of a funding Organisation creates an account so that the Organisation can publish programmes.",
        pre="Before this use case can be initiated, the visitor has accessed the Bursary-Bridge website and chosen to sign up as an Organisation.",
        steps=[
            "The Corporate User supplies a first name, last name, work email address, mobile number and password, and confirms the password.",
            "The Corporate User indicates whether to receive notifications by email.",
            "The Corporate User accepts the Terms of Service and Privacy Notice.",
            "The System validates every field and confirms the email address is not already registered.",
            "The System creates the account, an Organisation record and a session, and sends a verification email.",
            "The System opens the first step of the Organisation profile.",
        ],
        trigger="The Corporate User submits the organisation registration form.",
        precondition="The visitor is not signed in and does not hold an account under the supplied email address.",
        basic_path=[
            "The System validates the name fields, the work email address, the mobile number and the password.",
            "The System confirms that no account exists for the email address.",
            "The System hashes the password and creates the User record with the role Corporate.",
            "The System creates an Organisation record and links a Corporate profile to it.",
            "The System creates a session, sends a verification email and opens the Organisation Details step.",
        ],
        alternative_paths="None.",
        postcondition="A Corporate account, an Organisation record and a linked Corporate profile exist, and the Corporate User is signed in.",
        exception_paths="If the email address is already registered the registration is refused. Any field that fails validation is returned with a specific message and nothing is created.",
        other="The Organisation record is created immediately, so that every later action can be scoped to it. The Organisation is named properly in the next step.",
    ),
    dict(
        id="UC-16", name="Complete Organisation Profile", group="corporate", actor="Corporate User",
        brief="The Corporate User describes the Organisation, their role within it, and how it funds education.",
        pre="Before this use case can be initiated, the Corporate User has registered and is signed in.",
        steps=[
            "The Corporate User gives the Organisation's name, type, industry, website and country.",
            "The Corporate User states their own role, the size of the Organisation and their department.",
            "The Corporate User states whether the Organisation currently funds education, which kinds of programme it runs and roughly how many applications it receives each year.",
            "The Corporate User describes, optionally, how applications are managed today and the three biggest challenges faced.",
            "The System presents the whole profile for review, with a link to edit any section.",
            "The Corporate User confirms, and the System opens the Corporate Dashboard.",
        ],
        trigger="The Corporate User submits any step of the Organisation profile.",
        precondition="The Corporate User holds a valid session and a Corporate profile exists.",
        basic_path=[
            "The System presents the current step with any saved values filled in.",
            "The Corporate User completes the step and submits it.",
            "The System validates the step and writes the values against this Organisation only.",
            "The System advances the stored position and presents the next step.",
            "On confirmation the System marks the profile complete and opens the Dashboard.",
        ],
        alternative_paths="The Current Process step is optional and may be submitted empty.",
        postcondition="The Organisation profile is complete and the Corporate User may create funding programmes.",
        exception_paths="An Organisation name already used by another Organisation is refused. A step that fails validation is redisplayed with field errors. No more than three challenges may be selected.",
        other="Every write is scoped to the Organisation attached to the signed-in Corporate User, so one Organisation can never modify another's record.",
    ),
    dict(
        id="UC-17", name="Create Funding Programme", group="corporate", actor="Corporate User",
        brief="The Corporate User sets up a bursary, scholarship or grant for students to apply to.",
        pre="Before this use case can be initiated, the Corporate User has completed the Organisation profile and accessed the Programmes page.",
        steps=[
            "The Corporate User gives the programme name, a short description, a full description and the programme type.",
            "The Corporate User gives the date applications open and the date they close, and optionally the number of awards available.",
            "The Corporate User defines the eligibility criteria, as described in Section 2.2.3, Define Eligibility Criteria.",
            "The Corporate User selects what the programme pays for.",
            "The Corporate User selects the documents applicants must provide and adds any questions specific to this programme.",
            "The System presents the programme for review.",
            "The Corporate User saves the programme as a draft, or publishes it.",
        ],
        trigger="The Corporate User selects Create New Programme.",
        precondition="The Corporate User holds a valid session and the Organisation profile is complete.",
        basic_path=[
            "The System presents the programme builder at the first of its five steps.",
            "The Corporate User completes each step in turn.",
            "The System validates the whole programme, including that the closing date falls after the opening date.",
            "The System confirms that every selected institution and course exists in the catalogue.",
            "The System creates the programme, its eligibility rule, its supported lists and its questions in a single transaction.",
            "The System opens the new programme.",
        ],
        alternative_paths="The Corporate User may save the programme as a draft at any point and complete it later. A draft is not visible to students.",
        postcondition="A funding programme exists, together with its eligibility rule, supported courses and institutions, required documents and questions.",
        exception_paths="A closing date on or before the opening date is refused. A programme with no funding coverage selected is refused. A selected institution or course that is no longer in the catalogue is refused. The programme is written as one transaction, so it can never exist without its eligibility rule.",
        other="What the Corporate User configures here is exactly what the Matching Engine and the Eligibility Service evaluate; the criteria are stored as structured data rather than as prose.",
    ),
    dict(
        id="UC-18", name="Define Eligibility Criteria", group="corporate", actor="Corporate User",
        brief="The Corporate User states precisely who may apply to a funding programme.",
        pre="This use case is part of the Create Funding Programme use case. Before it can be initiated, the Corporate User has reached the Eligibility Criteria step of the programme builder.",
        steps=[
            "The Corporate User selects the institutions the programme supports, or leaves the list empty to accept any institution.",
            "The Corporate User selects the courses the programme supports, or leaves the list empty to accept any course.",
            "The Corporate User selects the qualification levels and years of study that qualify.",
            "The Corporate User sets a minimum academic average, if one applies.",
            "The Corporate User sets the citizenship, household income and provincial conditions, if any apply.",
            "The Corporate User records any further requirements in their own words.",
        ],
        trigger="The Corporate User reaches the Eligibility Criteria step of the programme builder.",
        precondition="A funding programme is being created or edited by a Corporate User of the owning Organisation.",
        basic_path=[
            "The System presents each criterion with the catalogue values available for it.",
            "The Corporate User sets the criteria that apply and leaves the rest empty.",
            "The System validates the values, including that any minimum average lies between zero and one hundred.",
            "The System stores the criteria as an eligibility rule attached to the programme.",
        ],
        alternative_paths="Any criterion left empty places no restriction on that dimension, and the System states this beneath each control.",
        postcondition="The programme carries an eligibility rule that the Matching Engine and the Eligibility Service can evaluate.",
        exception_paths="A minimum average outside the range zero to one hundred is refused.",
        other="This use case is part of Section 3.2.17, Create Funding Programme. The criteria drive both the match score shown to students and the eligibility verdict shown to the funder.",
    ),
    dict(
        id="UC-19", name="Publish Funding Programme", group="corporate", actor="Corporate User",
        brief="The Corporate User makes a programme visible to students, or closes it again.",
        pre="This use case extends the Create Funding Programme use case. Before it can be initiated, the Corporate User has opened a programme belonging to their Organisation.",
        steps=[
            "The Corporate User selects to publish the programme.",
            "The System confirms that the closing date has not already passed.",
            "The System sets the programme status to published.",
            "The programme immediately appears among the matches of every student whose profile fits it.",
            "The Corporate User may later close the programme, or reopen a closed programme.",
        ],
        trigger="The Corporate User selects to publish, close or reopen a programme.",
        precondition="The programme belongs to the Corporate User's Organisation.",
        basic_path=[
            "The System confirms the programme belongs to this Organisation.",
            "The System confirms that a programme being published still has a future closing date.",
            "The System updates the programme status.",
            "The System records the change in the audit log.",
        ],
        alternative_paths="Closing a programme withdraws it from student view but leaves applications already received untouched. A closed programme may be reopened.",
        postcondition="The programme status reflects the change, and student visibility follows from it.",
        exception_paths="Publishing a programme whose closing date has passed is refused, and the Corporate User is asked to set a future date first. A programme belonging to another Organisation returns a not found response.",
        other="This use case extends Section 3.2.17, Create Funding Programme.",
    ),
    dict(
        id="UC-20", name="View Applications", group="corporate", actor="Corporate User",
        brief="The Corporate User examines the applications submitted to the Organisation's programmes.",
        pre="Before this use case can be initiated, the Corporate User has signed in and accessed the Applications page.",
        steps=[
            "The System presents the applications submitted to this Organisation's programmes, best match first.",
            "The System presents counts by status across the top.",
            "The Corporate User may search by applicant name or email, or filter by programme, status, institution, course, match score or eligibility verdict.",
            "The System applies the filters and presents one page of results.",
            "The Corporate User may select several applicants and act on them together.",
        ],
        trigger="The Corporate User opens the Applications page or changes a filter.",
        precondition="The Corporate User holds a valid session and belongs to an Organisation.",
        basic_path=[
            "The System retrieves the applications belonging to this Organisation only.",
            "The System applies any search terms and filters in the database.",
            "The System counts the matching applications and retrieves one page of them.",
            "The System presents each applicant with their match score, eligibility verdict and status.",
        ],
        alternative_paths="The Corporate User may select applicants and shortlist, select or remove them in a single action.",
        postcondition="The Corporate User is presented with the applications that satisfy the chosen filters.",
        exception_paths="If no application satisfies the filters the System says so. An Organisation is never shown an application submitted to another Organisation's programme.",
        other="Filtering and paging are performed in the database, so a programme with several thousand applicants loads in constant time.",
    ),
    dict(
        id="UC-21", name="Review Applicant", group="corporate", actor="Corporate User",
        brief="The Corporate User examines one applicant in detail and assesses them against the programme's criteria.",
        pre="Before this use case can be initiated, the Corporate User has selected an applicant from the Applications list.",
        steps=[
            "The System presents the applicant's name, course, institution, match score, eligibility verdict and application status.",
            "The System presents the application details, contact information and academic summary.",
            "The System presents the applicant's study preferences and funding profile.",
            "The System evaluates the applicant against the programme's current criteria and presents every criterion.",
            "The System presents the documents attached and the answers given.",
            "The Corporate User may move to the previous or next applicant without returning to the list.",
        ],
        trigger="The Corporate User selects an applicant.",
        precondition="The application was submitted to a programme belonging to this Organisation.",
        basic_path=[
            "The System retrieves the application, confirming it belongs to this Organisation.",
            "The Eligibility Service evaluates the applicant against the programme's criteria as they stand now.",
            "The System presents the applicant across the overview, eligibility, documents and answers views.",
            "The System offers the review decisions available for this applicant.",
        ],
        alternative_paths="The Corporate User may open a document the applicant attached, which the System releases only because this Organisation received the application.",
        postcondition="The Corporate User has the information needed to make a decision on the applicant.",
        exception_paths="An application belonging to another Organisation returns a not found response.",
        other="Eligibility is recalculated when the applicant is opened, so a reviewer always sees an assessment against the programme's current criteria rather than a stale snapshot. Information the applicant has not supplied is reported as pending verification rather than counted as a failure.",
    ),
    dict(
        id="UC-22", name="Shortlist Applicant", group="corporate", actor="Corporate User",
        brief="The Corporate User marks an applicant as being under active consideration.",
        pre="This use case extends the Review Applicant use case. Before it can be initiated, the Corporate User has opened an applicant or selected applicants from the list.",
        steps=[
            "The Corporate User selects Add to Shortlist.",
            "The System sets the application status to Shortlisted and records a shortlist entry.",
            "The System notifies the applicant.",
            "The applicant appears on the Shortlists page for the programme.",
            "The Corporate User may later remove the applicant from the shortlist.",
        ],
        trigger="The Corporate User selects Add to Shortlist, on one applicant or on several at once.",
        precondition="The application was submitted to a programme belonging to this Organisation.",
        basic_path=[
            "The System confirms every named application belongs to this Organisation.",
            "The System records a shortlist entry for each and sets the application status to Shortlisted.",
            "The System notifies each applicant.",
            "The System records the action in the audit log.",
        ],
        alternative_paths="Removing an applicant from the shortlist returns the application to Under Review and withdraws the shortlist entry.",
        postcondition="The applicant holds the status Shortlisted and appears on the Organisation's shortlist.",
        exception_paths="An application belonging to another Organisation is refused. Selecting no applicant is refused.",
        other="This use case extends Section 3.2.21, Review Applicant. Applicants may be shortlisted individually or in bulk from the applications list.",
    ),
    dict(
        id="UC-23", name="Request Information from Applicant", group="corporate", actor="Corporate User",
        brief="The Corporate User asks an applicant for information or a document that is missing.",
        pre="This use case extends the Review Applicant use case. Before it can be initiated, the Corporate User has opened an applicant.",
        steps=[
            "The Corporate User selects Request Information.",
            "The Corporate User writes what is required.",
            "The System sets the application status to Documents Required and stores the message.",
            "The System notifies the applicant, quoting the message.",
            "The applicant sees the request on their application tracking page.",
        ],
        trigger="The Corporate User selects Request Information.",
        precondition="The application was submitted to a programme belonging to this Organisation.",
        basic_path=[
            "The System presents a field for the reviewer's message.",
            "The Corporate User writes the message and confirms.",
            "The System sets the status to Documents Required and stores the message against the application.",
            "The System notifies the applicant.",
        ],
        alternative_paths="None.",
        postcondition="The application holds the status Documents Required and the applicant has been told what is needed.",
        exception_paths="A request with no message is refused. An application belonging to another Organisation is refused.",
        other="This use case extends Section 3.2.21, Review Applicant.",
    ),
    dict(
        id="UC-24", name="Select Beneficiary", group="corporate", actor="Corporate User",
        brief="The Corporate User awards funding to an applicant, or records that an application was unsuccessful.",
        pre="This use case extends the Review Applicant use case. Before it can be initiated, the Corporate User has opened an applicant or selected applicants from the shortlist.",
        steps=[
            "The Corporate User selects Move to Selected.",
            "The System sets the application status to Approved and records the applicant as a beneficiary.",
            "The System notifies the applicant.",
            "The applicant appears on the Beneficiaries page.",
            "The Corporate User may instead reject an applicant, optionally giving a reason.",
        ],
        trigger="The Corporate User selects Move to Selected, or selects Reject.",
        precondition="The application was submitted to a programme belonging to this Organisation.",
        basic_path=[
            "The System confirms every named application belongs to this Organisation.",
            "The System sets the status to Approved and records the decision date.",
            "The System records or updates the shortlist entry as selected.",
            "The System notifies each applicant.",
        ],
        alternative_paths="Rejecting an applicant sets the status to Unsuccessful, records any reason given and notifies the applicant. An applicant may also be returned to Under Review.",
        postcondition="The applicant holds a final status of Approved or Unsuccessful and has been notified.",
        exception_paths="An application belonging to another Organisation is refused.",
        other="This use case extends Section 3.2.21, Review Applicant. Selection may be performed on one applicant or on several at once from the shortlist.",
    ),
    dict(
        id="UC-25", name="View Reports", group="corporate", actor="Corporate User",
        brief="The Corporate User reviews the Organisation's application pipeline and reach.",
        pre="Before this use case can be initiated, the Corporate User has signed in and accessed the Reports page.",
        steps=[
            "The System presents the totals for applications received, applicants found eligible, applicants shortlisted and beneficiaries selected.",
            "The System presents the breakdown of applications by status.",
            "The System presents the breakdown of applicants by province.",
            "The System presents each programme with its application volume, eligible count and eligibility rate.",
            "The System presents the institutions the Organisation's applicants come from.",
        ],
        trigger="The Corporate User opens the Reports page.",
        precondition="The Corporate User holds a valid session and belongs to an Organisation.",
        basic_path=[
            "The System groups this Organisation's applications by status, by province and by institution.",
            "The System computes the eligibility rate and conversion rate for each programme.",
            "The System presents the figures as totals, proportions and tables.",
        ],
        alternative_paths="None.",
        postcondition="The Corporate User is presented with the Organisation's pipeline and reach.",
        exception_paths="If the Organisation has received no applications, the System says so rather than presenting empty charts.",
        other="Every figure is computed from this Organisation's own applications. Eligibility counts read the verdict recorded when each application was submitted.",
    ),
]

# ---------------------------------------------------------------------------
# 2.4 / 3.3  Non-functional requirements
# ---------------------------------------------------------------------------
NON_FUNCTIONAL = [
    ("Platform", "Bursary-Bridge is a responsive web application. It is reached through a current web browser on a desktop computer, a laptop, a tablet or a mobile telephone, and requires no installation."),
    ("Server", "The application runs on a Node.js server and stores its data in a PostgreSQL database. Both may run on a single machine for the prototype, and may be separated as demand grows."),
    ("Responsiveness", "The interface is laid out for desktop, laptop, tablet and mobile widths. On a narrow screen the navigation collapses behind a menu and the layout reflows; no page requires horizontal scrolling."),
    ("Performance", "Lists that may grow large, in particular the applicant list, are filtered and paged in the database so that the browser never receives more than one page of results."),
    ("Availability", "The application is intended to be available at all times, subject to the hosting arrangements of the deploying institution."),
    ("Accessibility", "The interface uses semantic HTML, labelled form controls, visible keyboard focus and sufficient colour contrast, so that it can be used with a keyboard alone and with a screen reader."),
    ("Usability", "Each screen states where the User is, what is required of them and why it is required. Every list presents a meaningful empty state, and every operation presents a loading, success and error state. Users are never shown a technical error message."),
]

SECURITY = [
    "Passwords are hashed with bcrypt at cost twelve and are never written to logs.",
    "Sessions are random values held in an HTTP-only cookie. Only a hash of the session token is stored, so a copy of the database cannot be replayed as a login. Logging out deletes the session, and changing a password ends every other session.",
    "An unknown email address and an incorrect password produce identical responses, so the login endpoint cannot be used to discover which addresses hold accounts.",
    "Registration, login, verification email requests, document uploads and application submissions are rate limited, per address and per account.",
    "Every request is authorised on the server before any data is read. A Student may read only their own profile, applications and documents. A Corporate User may read only the programmes and applications belonging to their own Organisation. These rules are applied in the database query rather than in the interface.",
    "Uploaded documents are stored outside the public web root and are released only through an authorised handler, which admits the Student who owns the document and any Organisation that has received an application the document is attached to.",
    "Every field is validated on the server. The rules shown in the browser are generated from the same definitions, so the two cannot diverge.",
    "Changes to applications, programmes, shortlists and accounts are written to an append-only audit log.",
]

DATA_ENTITIES = [
    ("User", [
        ("Email Address", "Text", "The address used to sign in", "Unique across the system"),
        ("Password Hash", "Text", "The bcrypt hash of the password", "The password itself is never stored"),
        ("Role", "Enumeration", "Student or Corporate", "Determines which part of the system is reachable"),
        ("First Name", "Text", "Given name", ""),
        ("Last Name", "Text", "Family name", ""),
        ("Mobile Number", "Text", "South African mobile number", ""),
        ("Email Verified", "Date", "When the address was confirmed; null if not", ""),
    ]),
    ("Student Profile", [
        ("User", "Pointer", "The User entity", "One profile per User"),
        ("Education Stage", "Enumeration", "Grade 10 through postgraduate, or planning to study", ""),
        ("Qualification Level", "Enumeration", "Certificate through doctoral degree", "Not asked of school learners"),
        ("Study Status", "Enumeration", "Enrolled, accepted, applied, planning or returning", ""),
        ("Academic Average", "Integer", "Latest average as a percentage", "Null if the Student does not know it"),
        ("Household Income", "Enumeration", "Annual household income band", "A band, never an exact figure"),
        ("Citizenship", "Enumeration", "Citizen, permanent resident or other", ""),
        ("Province", "Enumeration", "One of the nine South African provinces", ""),
        ("Profile Strength", "Integer", "Completeness as a percentage", "Recalculated after every change"),
    ]),
    ("Study Preference", [
        ("Student Profile", "Pointer", "The Student entity", ""),
        ("Preference Number", "Integer", "Position in the Student's ordered list", "One to six"),
        ("Programme", "Pointer", "The course entity", "Paired with the institution below"),
        ("Institution", "Pointer", "The institution entity", "Paired with the course above"),
    ]),
    ("Organisation", [
        ("Name", "Text", "Registered name of the Organisation", "Unique across the system"),
        ("Type", "Enumeration", "Corporation, foundation, NGO or other", ""),
        ("Industry", "Enumeration", "Sector in which the Organisation operates", ""),
        ("Website", "Text", "Public web address", "Optional"),
        ("Application Volume", "Enumeration", "Applications received each year", ""),
    ]),
    ("Funding Programme", [
        ("Organisation", "Pointer", "The owning Organisation", "Scopes every access to the programme"),
        ("Name", "Text", "Name of the programme", ""),
        ("Funding Type", "Enumeration", "Bursary, scholarship, grant or other", ""),
        ("Coverage", "Enumeration", "What the programme pays for", "May be several"),
        ("Open Date", "Date", "When applications open", ""),
        ("Closing Date", "Date", "When applications close", ""),
        ("Status", "Enumeration", "Draft, published or closed", "Only published programmes are visible to students"),
    ]),
    ("Eligibility Rule", [
        ("Funding Programme", "Pointer", "The programme the rule governs", "One rule per programme"),
        ("Minimum Academic Average", "Integer", "Lowest acceptable average", "Null if no minimum applies"),
        ("Qualification Levels", "Enumeration", "Levels that qualify", "Empty means all levels"),
        ("Years of Study", "Integer", "Years that qualify", "Empty means any year"),
        ("Citizenship", "Enumeration", "Citizenship conditions", "Empty means no condition"),
        ("Maximum Household Income", "Enumeration", "Highest acceptable income band", "Null if no condition"),
        ("Provinces", "Enumeration", "Provinces that qualify", "Empty means all provinces"),
        ("Required Documents", "Enumeration", "Documents applicants must provide", ""),
    ]),
    ("Application", [
        ("Student Profile", "Pointer", "The applying Student", ""),
        ("Funding Programme", "Pointer", "The programme applied to", "One application per Student per programme"),
        ("Organisation", "Pointer", "The Organisation that receives it", "Scopes funder access"),
        ("Status", "Enumeration", "Draft through to approved or unsuccessful", ""),
        ("Match Score", "Integer", "The score at the moment of submission", "Held so the funder sees a stable figure"),
        ("Eligibility Outcome", "Enumeration", "Eligible, not eligible or pending verification", "Recorded at submission"),
        ("Answers", "Text", "Answers to the programme's questions", ""),
        ("Submitted", "Date", "When the application was submitted", "Null while it remains a draft"),
    ]),
    ("Shortlist", [
        ("Application", "Pointer", "The application concerned", "One entry per application"),
        ("Organisation", "Pointer", "The Organisation shortlisting", ""),
        ("Status", "Enumeration", "Shortlisted, selected or withdrawn", ""),
        ("Added", "Date", "When the applicant was shortlisted", ""),
        ("Selected", "Date", "When the applicant was selected", "Null unless selected"),
    ]),
    ("Document", [
        ("Student Profile", "Pointer", "The owning Student", "Governs who may read the file"),
        ("Type", "Enumeration", "Identity document, academic record, proof of income and so on", ""),
        ("File Name", "Text", "Name of the uploaded file", ""),
        ("Size", "Integer", "Size of the file in bytes", "Limited to five megabytes"),
        ("Storage Key", "Text", "Where the file is held in storage", "Outside the public web root"),
    ]),
]
